version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8.0

    steps:
      - checkout

#      - restore_cache:
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: Set up pipenv and install requirements
          command: |
            sudo pip install pipenv
            pipenv install

#      - save_cache:
#          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#          paths:
#            - ./venv

      - run:
          name: Compile files
          command: |
            pipenv run python -m compileall main.py modules utils -fq
